version: '3.5'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        hostname: nginx
        volumes:
            - ./app:/app
            - ./sites.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8888:80"
        depends_on:
            - "php"
        tty: true
        restart: always

    php:
        image: php:7-fpm-alpine
        container_name: php
        hostname: php
        volumes:
            - ./app:/app
        tty: true
        restart: always